"""verze3

Revision ID: 20250121_verze3
Revises: 20250121_verze2
Create Date: 2025-01-21 18:00:00.571450+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250121_verze3'
down_revision = '20250121_verze2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
