"""verze1

Revision ID: 20250121_verze1
Revises: 20241210_v2
Create Date: 2025-01-21 17:52:16.366348+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250121_verze1'
down_revision = '20241210_v2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logins',
    sa.Column('login_id', sa.Integer(), nullable=False),
    sa.Column('jmeno', sa.String(length=50), nullable=False),
    sa.Column('prijmeni', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('login_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logins')
    # ### end Alembic commands ###
